language: node_js
node_js:
  - 'node'

jobs:
  include:
    - stage: test
      node_js:
        - '6'
        - 'node'
      script: npm test
    - stage: coverage-report
      script: npm run coverage:ci
    - stage: code-quality
      script: npm run tslint